---
- hosts: localhost
  remote_user: root
  gather_facts: false

  tasks:

  - name: 准备cfssl工具
    unarchive: src=tls/cfssl.tar.gz dest=/usr/local/bin mode=u+x

  - name: 生成etcd证书
    shell: |
      cd tls/cert
      cfssl gencert -initca ca-csr.json | cfssljson -bare ca -
      cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=www server-csr.json | cfssljson -bare server